/* Database schema to keep the structure of entire database. */
CREATE DATABASE vet_clinic;

CREATE TABLE animals (
    name varchar(100),
    id int  GENERATED BY DEFAULT AS IDENTITY,
    date_of_birth date,
    escape_attempts int,
    neutered bit,
    weight_kg decimal
);